// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/3de2726e83e2995643b2907359a092408172fa30/node-uuid/node-uuid-cjs.d.ts
declare module "node-uuid" {
    var uuid: __NodeUUID.UUID;
    export = uuid;
}
